# Importing Required Libraries

In [1]:
import torch
from torch.utils.data import DataLoader
from torch import nn
import pandas as pd
import numpy as np
from torch.utils.data import DataLoader, Dataset
import matplotlib.pyplot as plt

# Reading Data

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
train.describe()

,id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,...,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.00000,...,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.00000,200000.000000
mean,99999.500000,0.972710,1.168365,2.219325,2.296735,0.793530,1.431105,1.010695,0.673090,1.94398,...,1.798040,0.508695,1.827300,0.910370,1.603585,1.219210,0.806895,1.282925,2.94021,0.632005
std,57735.171256,3.941836,3.993407,6.476570,7.551858,2.935785,5.162746,3.949231,2.234949,3.93133,...,5.053014,1.867330,7.188924,3.835182,4.877679,4.826003,2.458741,4.261420,10.78465,3.925310
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,49999.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,99999.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
75%,149999.250000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.00000,...,1.000000,0.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.00000,0.000000
max,199999.000000,61.000000,51.000000,64.000000,70.000000,38.000000,76.000000,43.000000,30.000000,38.00000,...,54.000000,24.000000,79.000000,55.000000,65.000000,67.000000,30.000000,61.000000,130.00000,52.000000

# Preprocessing Data

In [3]:
train.drop(axis = 1, labels = 'id', inplace = True)

y_train = train['target']
x_train = train.drop(axis = 1, labels = 'target', inplace = False)
x_train /= 200
x_train.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74
0,0.000,0.0,0.030,0.005,0.000,0.000,0.00,0.000,0.035,0.000,...,0.015,0.00,0.00,0.0,0.00,0.000,0.0,0.01,0.000,0.0
1,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.01,0.00,0.0,0.00,0.000,0.0,0.00,0.005,0.0
2,0.000,0.0,0.000,0.000,0.000,0.005,0.00,0.015,0.000,0.000,...,0.040,0.00,0.00,0.0,0.00,0.005,0.0,0.00,0.000,0.0
3,0.000,0.0,0.035,0.000,0.005,0.025,0.01,0.010,0.000,0.005,...,0.000,0.00,0.02,0.0,0.01,0.010,0.0,0.02,0.015,0.0
4,0.005,0.0,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.00,0.00,0.0,0.00,0.000,0.0,0.00,0.000,0.0

In [5]:
alpha = [f"Class_{i}" for i in range(1,10)]
num = [i for i in range(0,9)]
y_train.replace(alpha,num,inplace=True)
y_train.value_counts()

5    51811
7    51763
8    25542
1    24431
2    14798
6    14769
0     9118
3     4704
4     3064
Name: target, dtype: int64

In [ ]:
#Converting DataFrame to Tensor

train_x = torch.tensor(x_train.values.astype(np.float32)) 
train_y = torch.tensor(y_train.values.astype(np.int64))
train_x[0], train_y[0]

# Importing the Data into DataLoader

In [ ]:
#Combining labels and feature tensor to prepare for DataLoader Function 

class mydataset(Dataset):
    def __init__(self, data, labels):
        self.labels = labels
        self.data = data
    def __len__(self):
        return len(self.labels)
    def __getitem__(self,i):
        item = self.data[i]
        label = self.labels[i]
        return (item,label)
    
training_data = mydataset(train_x,train_y)

# Model

In [ ]:
class NN(nn.Module):
    def __init__(self):
        super().__init__()
        self.sequence = nn.Sequential(
            nn.Linear(75,32),
            nn.BatchNorm1d(num_features = 32), # normalize inputs across all the batches
            nn.ReLU(),
            nn.Linear(32, 32),
            nn.BatchNorm1d(num_features = 32),
            nn.ReLU(),
            nn.Linear(32,9),
            nn.ReLU()
        )
    def forward(self,x):
        output = self.sequence(x)
        return output

# Hyper-Parameters

In [ ]:
model = NN()
loss_fn = nn.CrossEntropyLoss()
epochs = 100
lr_rate = .05

optimiser = torch.optim.Adam(model.parameters(),lr = lr_rate)

# Training The Model

In [ ]:
def train_loop(dataloader, model, loss_fn, optimiser):
    size = len(dataloader.dataset)
    train_loss, correct = 0.0, 0
    for X, y in dataloader:
        pred = model(X)
        loss = loss_fn(pred, y)
        train_loss += loss.item() # Adding loss across all batches
        optimiser.zero_grad()
        loss.backward()
        optimiser.step()
        correct += ((nn.functional.softmax(pred, dim = 1)).argmax(1) == y).type(torch.float).sum().item()
        #Adding Accuracy across all batches
        
    train_loss /= size #mean of loss
    correct /= size  #mean of accuracy     
    print(f"Train Loss: {train_loss:.3f}")
    print(f"Train Accuracy: {correct:.3f}")
    return train_loss

In [ ]:
total_train_loss = []
for i in range(epochs):
    train_dataloader = DataLoader(training_data, batch_size = 40, shuffle = True)
    print(f"[=================== Epoch: {i+1} ==================]")
    train_los = train_loop(train_dataloader, model, loss_fn, optimiser)
    total_train_loss.append(train_los)

# Plotting Loss

In [ ]:
plt.plot(total_train_loss)
plt.xlabel("No. of Iteration")
plt.ylabel("LOSS")
plt.show

# Test-Set

In [ ]:
iden = test["id"].copy()
test.drop(axis = 1, labels = 'id', inplace = True)

y = nn.functional.softmax(model(torch.tensor(test.values.astype(np.float32))),dim=1)
ans = pd.DataFrame(y.detach().numpy())

lis = [f"Class_{i}" for i in range(1,10)]
ans.columns = lis
ans = pd.concat([iden,ans],axis = 1)

for i in range(1,10):
    ans[f"Class_{i}"] = ans[f"Class_{i}"].round(decimals = 4)
ans.head()

In [ ]:
ans.to_csv('hackathon.csv',index = False,header = True)